apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  postgres-root-username: cG9zdGdyZXM=
  postgres-root-password: cG9zdGdyZXM=