apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

Parameters:
  Region:
  Type: String
metadata:
  name: cluster-3
  region: !Ref Region

nodeGroups:
  - name: ng1-public
    instanceType: m5.xlarge
    instanceName: custom-node-name
    desiredCapacity: 4
  - name: ng2-private
    instanceType: m5.large
    desiredCapacity: 10
    privateNetworking: true
